/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowclient (void)
{
  GtkWidget *windowclient;
  GtkWidget *KKfixed0;
  GtkWidget *KKbuttonmenuprincipal;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label1;
  GtkWidget *image1;
  GtkWidget *KKnotebook;
  GtkWidget *KKfixed1;
  GtkWidget *KKentryid;
  GtkWidget *KKbuttonactualiser;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *KKbuttonmodifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *KKbuttonrechercher;
  GtkWidget *image6;
  GtkWidget *label34;
  GtkWidget *KKbuttonsupprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *KKscrolledwindow;
  GtkWidget *KKtreeview;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label_nompren;
  GtkWidget *label_max_paiments;
  GtkWidget *label35;
  GtkWidget *topclientref;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label37;
  GtkWidget *KKlabelpageprincipale;
  GtkWidget *KKfixed2;
  GtkWidget *KKentryajoutid;
  GtkWidget *KKentryajoutnp;
  GtkWidget *KKentryajoutvaleur;
  GtkObject *KKspinbuttonajoutjour_adj;
  GtkWidget *KKspinbuttonajoutjour;
  GtkObject *KKspinbuttonajoutmois_adj;
  GtkWidget *KKspinbuttonajoutmois;
  GtkObject *KKspinbuttonajoutannee_adj;
  GtkWidget *KKspinbuttonajoutannee;
  GtkWidget *KKlabelmsgsucc;
  GtkWidget *KKbuttonajouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label22;
  GtkWidget *KKcomboboxajoutsexe;
  GtkWidget *KKlabelajoutvaleur;
  GtkWidget *KKlabelajoutdate;
  GtkWidget *KKlabelajoutnp;
  GtkWidget *KKlabelajoutid;
  GtkWidget *KKlabelajoutsexe;
  GtkWidget *label32;
  GtkWidget *KKlabelajouter;
  GtkWidget *KKfixed3;
  GtkWidget *KKentrymodifnp;
  GtkWidget *KKentrymodifvaleur;
  GtkObject *KKspinbuttonmodifjour_adj;
  GtkWidget *KKspinbuttonmodifjour;
  GtkObject *KKspinbuttonmodifmois_adj;
  GtkWidget *KKspinbuttonmodifmois;
  GtkObject *KKspinbuttonmodifannee_adj;
  GtkWidget *KKspinbuttonmodifannee;
  GtkWidget *KKbuttonconfirmermodif;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label30;
  GtkWidget *KKcomboboxmodifsexe;
  GtkWidget *KKlabelmodifreus;
  GtkWidget *KKentrymodifid;
  GtkWidget *KKlabelmodifsexe;
  GtkWidget *KKlabelmodifid;
  GtkWidget *KKlabelmodifnp;
  GtkWidget *KKlabelmodifvaleur;
  GtkWidget *KKlabelmodifdate;
  GtkWidget *label33;
  GtkWidget *label31;

  windowclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowclient), _("Gestion des clients"));

  KKfixed0 = gtk_fixed_new ();
  gtk_widget_show (KKfixed0);
  gtk_container_add (GTK_CONTAINER (windowclient), KKfixed0);

  KKbuttonmenuprincipal = gtk_button_new ();
  gtk_widget_show (KKbuttonmenuprincipal);
  gtk_fixed_put (GTK_FIXED (KKfixed0), KKbuttonmenuprincipal, 488, 176);
  gtk_widget_set_size_request (KKbuttonmenuprincipal, 136, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (KKbuttonmenuprincipal), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Menu principal"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  image1 = create_pixmap (windowclient, "130735738_1498363350353443_8703009305772898258_n.jpg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (KKfixed0), image1, 0, 0);
  gtk_widget_set_size_request (image1, 624, 176);

  KKnotebook = gtk_notebook_new ();
  gtk_widget_show (KKnotebook);
  gtk_fixed_put (GTK_FIXED (KKfixed0), KKnotebook, 0, 208);
  gtk_widget_set_size_request (KKnotebook, 624, 504);

  KKfixed1 = gtk_fixed_new ();
  gtk_widget_show (KKfixed1);
  gtk_container_add (GTK_CONTAINER (KKnotebook), KKfixed1);

  KKentryid = gtk_entry_new ();
  gtk_widget_show (KKentryid);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKentryid, 40, 56);
  gtk_widget_set_size_request (KKentryid, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentryid), 8226);

  KKbuttonactualiser = gtk_button_new ();
  gtk_widget_show (KKbuttonactualiser);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKbuttonactualiser, 56, 400);
  gtk_widget_set_size_request (KKbuttonactualiser, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (KKbuttonactualiser), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  KKbuttonmodifier = gtk_button_new ();
  gtk_widget_show (KKbuttonmodifier);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKbuttonmodifier, 424, 400);
  gtk_widget_set_size_request (KKbuttonmodifier, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (KKbuttonmodifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  KKbuttonrechercher = gtk_button_new ();
  gtk_widget_show (KKbuttonrechercher);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKbuttonrechercher, 240, 56);
  gtk_widget_set_size_request (KKbuttonrechercher, 32, 32);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (KKbuttonrechercher), image6);

  label34 = gtk_label_new (_("<b><span foreground =\"black\">recherche (id - nom prenom - sexe)</span> </b>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label34, 16, 16);
  gtk_widget_set_size_request (label34, 296, 32);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  KKbuttonsupprimer = gtk_button_new ();
  gtk_widget_show (KKbuttonsupprimer);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKbuttonsupprimer, 256, 400);
  gtk_widget_set_size_request (KKbuttonsupprimer, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (KKbuttonsupprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  KKscrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (KKscrolledwindow);
  gtk_fixed_put (GTK_FIXED (KKfixed1), KKscrolledwindow, 16, 128);
  gtk_widget_set_size_request (KKscrolledwindow, 584, 256);

  KKtreeview = gtk_tree_view_new ();
  gtk_widget_show (KKtreeview);
  gtk_container_add (GTK_CONTAINER (KKscrolledwindow), KKtreeview);
  gtk_widget_set_size_request (KKtreeview, 568, 288);

  label38 = gtk_label_new (_("<b><span foreground =\"red\">Nom et Prenom</span></b>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label38, 336, 48);
  gtk_widget_set_size_request (label38, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label39 = gtk_label_new (_("<b><span foreground =\"red\">Encaissement</span></b>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label39, 336, 80);
  gtk_widget_set_size_request (label39, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label_nompren = gtk_label_new (_("<span foreground =\"green\">nom  et prenom</span>"));
  gtk_widget_show (label_nompren);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label_nompren, 456, 48);
  gtk_widget_set_size_request (label_nompren, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_nompren), TRUE);

  label_max_paiments = gtk_label_new (_("<span foreground =\"green\">encaissement</span>"));
  gtk_widget_show (label_max_paiments);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label_max_paiments, 456, 80);
  gtk_widget_set_size_request (label_max_paiments, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_max_paiments), TRUE);

  label35 = gtk_label_new (_("<b><span foreground =\"red\">Meilleur client</span> </b>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (KKfixed1), label35, 456, 16);
  gtk_widget_set_size_request (label35, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  topclientref = gtk_button_new ();
  gtk_widget_show (topclientref);
  gtk_fixed_put (GTK_FIXED (KKfixed1), topclientref, 352, 16);
  gtk_widget_set_size_request (topclientref, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (topclientref), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox7), label37, FALSE, FALSE, 0);

  KKlabelpageprincipale = gtk_label_new (_("<b>Liste des clients</b>"));
  gtk_widget_show (KKlabelpageprincipale);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (KKnotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (KKnotebook), 0), KKlabelpageprincipale);
  gtk_label_set_use_markup (GTK_LABEL (KKlabelpageprincipale), TRUE);
  gtk_label_set_justify (GTK_LABEL (KKlabelpageprincipale), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (KKlabelpageprincipale), 0.5, 0.53);

  KKfixed2 = gtk_fixed_new ();
  gtk_widget_show (KKfixed2);
  gtk_container_add (GTK_CONTAINER (KKnotebook), KKfixed2);

  KKentryajoutid = gtk_entry_new ();
  gtk_widget_show (KKentryajoutid);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKentryajoutid, 312, 112);
  gtk_widget_set_size_request (KKentryajoutid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentryajoutid), 8226);

  KKentryajoutnp = gtk_entry_new ();
  gtk_widget_show (KKentryajoutnp);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKentryajoutnp, 312, 160);
  gtk_widget_set_size_request (KKentryajoutnp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentryajoutnp), 8226);

  KKentryajoutvaleur = gtk_entry_new ();
  gtk_widget_show (KKentryajoutvaleur);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKentryajoutvaleur, 312, 208);
  gtk_widget_set_size_request (KKentryajoutvaleur, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentryajoutvaleur), 8226);

  KKspinbuttonajoutjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  KKspinbuttonajoutjour = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonajoutjour_adj), 1, 0);
  gtk_widget_show (KKspinbuttonajoutjour);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKspinbuttonajoutjour, 304, 256);
  gtk_widget_set_size_request (KKspinbuttonajoutjour, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonajoutjour), TRUE);

  KKspinbuttonajoutmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  KKspinbuttonajoutmois = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonajoutmois_adj), 1, 0);
  gtk_widget_show (KKspinbuttonajoutmois);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKspinbuttonajoutmois, 368, 256);
  gtk_widget_set_size_request (KKspinbuttonajoutmois, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonajoutmois), TRUE);

  KKspinbuttonajoutannee_adj = gtk_adjustment_new (1990, 1950, 2002, 1, 10, 3000);
  KKspinbuttonajoutannee = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonajoutannee_adj), 1, 0);
  gtk_widget_show (KKspinbuttonajoutannee);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKspinbuttonajoutannee, 432, 256);
  gtk_widget_set_size_request (KKspinbuttonajoutannee, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonajoutannee), TRUE);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (KKspinbuttonajoutannee), TRUE);

  KKlabelmsgsucc = gtk_label_new ("");
  gtk_widget_show (KKlabelmsgsucc);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelmsgsucc, 144, 312);
  gtk_widget_set_size_request (KKlabelmsgsucc, 320, 56);

  KKbuttonajouter = gtk_button_new ();
  gtk_widget_show (KKbuttonajouter);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKbuttonajouter, 232, 400);
  gtk_widget_set_size_request (KKbuttonajouter, 128, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (KKbuttonajouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  KKcomboboxajoutsexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (KKcomboboxajoutsexe);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKcomboboxajoutsexe, 312, 56);
  gtk_widget_set_size_request (KKcomboboxajoutsexe, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (KKcomboboxajoutsexe), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (KKcomboboxajoutsexe), _("Femme"));

  KKlabelajoutvaleur = gtk_label_new (_("Encaissement: "));
  gtk_widget_show (KKlabelajoutvaleur);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelajoutvaleur, 112, 216);
  gtk_widget_set_size_request (KKlabelajoutvaleur, 128, 24);

  KKlabelajoutdate = gtk_label_new (_("Date de naissance: "));
  gtk_widget_show (KKlabelajoutdate);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelajoutdate, 112, 256);
  gtk_widget_set_size_request (KKlabelajoutdate, 161, 32);

  KKlabelajoutnp = gtk_label_new (_("Nom et Prenom: "));
  gtk_widget_show (KKlabelajoutnp);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelajoutnp, 104, 160);
  gtk_widget_set_size_request (KKlabelajoutnp, 161, 24);

  KKlabelajoutid = gtk_label_new (_("Identifiant du client: "));
  gtk_widget_show (KKlabelajoutid);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelajoutid, 112, 112);
  gtk_widget_set_size_request (KKlabelajoutid, 177, 24);

  KKlabelajoutsexe = gtk_label_new (_("Sexe: "));
  gtk_widget_show (KKlabelajoutsexe);
  gtk_fixed_put (GTK_FIXED (KKfixed2), KKlabelajoutsexe, 80, 56);
  gtk_widget_set_size_request (KKlabelajoutsexe, 153, 25);

  label32 = gtk_label_new (_("<b><span foreground =\"red\">Ajouter  les donnes d'un client</span></b>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (KKfixed2), label32, 216, 0);
  gtk_widget_set_size_request (label32, 240, 40);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label32), 0.5, 0.33);

  KKlabelajouter = gtk_label_new (_("<b>Ajout d'un client</b>"));
  gtk_widget_show (KKlabelajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (KKnotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (KKnotebook), 1), KKlabelajouter);
  gtk_label_set_use_markup (GTK_LABEL (KKlabelajouter), TRUE);
  gtk_misc_set_alignment (GTK_MISC (KKlabelajouter), 0.5, 0.33);

  KKfixed3 = gtk_fixed_new ();
  gtk_widget_show (KKfixed3);
  gtk_container_add (GTK_CONTAINER (KKnotebook), KKfixed3);

  KKentrymodifnp = gtk_entry_new ();
  gtk_widget_show (KKentrymodifnp);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKentrymodifnp, 312, 152);
  gtk_widget_set_size_request (KKentrymodifnp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentrymodifnp), 8226);

  KKentrymodifvaleur = gtk_entry_new ();
  gtk_widget_show (KKentrymodifvaleur);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKentrymodifvaleur, 312, 192);
  gtk_widget_set_size_request (KKentrymodifvaleur, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentrymodifvaleur), 8226);

  KKspinbuttonmodifjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  KKspinbuttonmodifjour = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonmodifjour_adj), 1, 0);
  gtk_widget_show (KKspinbuttonmodifjour);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKspinbuttonmodifjour, 304, 232);
  gtk_widget_set_size_request (KKspinbuttonmodifjour, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonmodifjour), TRUE);

  KKspinbuttonmodifmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  KKspinbuttonmodifmois = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonmodifmois_adj), 1, 0);
  gtk_widget_show (KKspinbuttonmodifmois);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKspinbuttonmodifmois, 368, 232);
  gtk_widget_set_size_request (KKspinbuttonmodifmois, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonmodifmois), TRUE);

  KKspinbuttonmodifannee_adj = gtk_adjustment_new (1990, 1950, 2002, 1, 10, 10);
  KKspinbuttonmodifannee = gtk_spin_button_new (GTK_ADJUSTMENT (KKspinbuttonmodifannee_adj), 1, 0);
  gtk_widget_show (KKspinbuttonmodifannee);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKspinbuttonmodifannee, 432, 232);
  gtk_widget_set_size_request (KKspinbuttonmodifannee, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (KKspinbuttonmodifannee), TRUE);

  KKbuttonconfirmermodif = gtk_button_new ();
  gtk_widget_show (KKbuttonconfirmermodif);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKbuttonconfirmermodif, 240, 384);
  gtk_widget_set_size_request (KKbuttonconfirmermodif, 128, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (KKbuttonconfirmermodif), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, FALSE, FALSE, 0);

  KKcomboboxmodifsexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (KKcomboboxmodifsexe);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKcomboboxmodifsexe, 312, 56);
  gtk_widget_set_size_request (KKcomboboxmodifsexe, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (KKcomboboxmodifsexe), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (KKcomboboxmodifsexe), _("Femme"));

  KKlabelmodifreus = gtk_label_new ("");
  gtk_widget_show (KKlabelmodifreus);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifreus, 152, 304);
  gtk_widget_set_size_request (KKlabelmodifreus, 320, 56);

  KKentrymodifid = gtk_entry_new ();
  gtk_widget_show (KKentrymodifid);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKentrymodifid, 312, 104);
  gtk_widget_set_size_request (KKentrymodifid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (KKentrymodifid), 8226);

  KKlabelmodifsexe = gtk_label_new (_("Sexe: "));
  gtk_widget_show (KKlabelmodifsexe);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifsexe, 72, 56);
  gtk_widget_set_size_request (KKlabelmodifsexe, 153, 25);

  KKlabelmodifid = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (KKlabelmodifid);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifid, 112, 112);
  gtk_widget_set_size_request (KKlabelmodifid, 96, 16);

  KKlabelmodifnp = gtk_label_new (_("Nom et Prenom: "));
  gtk_widget_show (KKlabelmodifnp);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifnp, 96, 152);
  gtk_widget_set_size_request (KKlabelmodifnp, 161, 24);

  KKlabelmodifvaleur = gtk_label_new (_("Encaissement:"));
  gtk_widget_show (KKlabelmodifvaleur);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifvaleur, 88, 192);
  gtk_widget_set_size_request (KKlabelmodifvaleur, 160, 32);

  KKlabelmodifdate = gtk_label_new (_("Date de naissance: "));
  gtk_widget_show (KKlabelmodifdate);
  gtk_fixed_put (GTK_FIXED (KKfixed3), KKlabelmodifdate, 104, 232);
  gtk_widget_set_size_request (KKlabelmodifdate, 161, 32);

  label33 = gtk_label_new (_("<b><span foreground =\"red\">Modifier les donnees d'un client</span></b>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (KKfixed3), label33, 184, 8);
  gtk_widget_set_size_request (label33, 272, 32);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label33), 0.5, 0.33);

  label31 = gtk_label_new (_("<b>Modifier un client</b>"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (KKnotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (KKnotebook), 2), label31);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label31), 0.5, 0.33);

  g_signal_connect ((gpointer) KKbuttonmenuprincipal, "clicked",
                    G_CALLBACK (on_KKbuttonmenuprincipal_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonactualiser, "clicked",
                    G_CALLBACK (on_KKbuttonactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonmodifier, "clicked",
                    G_CALLBACK (on_KKbuttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonrechercher, "clicked",
                    G_CALLBACK (on_KKbuttonrechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonsupprimer, "clicked",
                    G_CALLBACK (on_KKbuttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKtreeview, "row_activated",
                    G_CALLBACK (on_KKtreeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) topclientref, "clicked",
                    G_CALLBACK (on_topclientref_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonajouter, "clicked",
                    G_CALLBACK (on_KKbuttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) KKbuttonconfirmermodif, "clicked",
                    G_CALLBACK (on_KKbuttonconfirmermodif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowclient, windowclient, "windowclient");
  GLADE_HOOKUP_OBJECT (windowclient, KKfixed0, "KKfixed0");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonmenuprincipal, "KKbuttonmenuprincipal");
  GLADE_HOOKUP_OBJECT (windowclient, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowclient, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowclient, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowclient, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowclient, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowclient, KKnotebook, "KKnotebook");
  GLADE_HOOKUP_OBJECT (windowclient, KKfixed1, "KKfixed1");
  GLADE_HOOKUP_OBJECT (windowclient, KKentryid, "KKentryid");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonactualiser, "KKbuttonactualiser");
  GLADE_HOOKUP_OBJECT (windowclient, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowclient, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowclient, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowclient, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonmodifier, "KKbuttonmodifier");
  GLADE_HOOKUP_OBJECT (windowclient, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowclient, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowclient, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowclient, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonrechercher, "KKbuttonrechercher");
  GLADE_HOOKUP_OBJECT (windowclient, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowclient, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonsupprimer, "KKbuttonsupprimer");
  GLADE_HOOKUP_OBJECT (windowclient, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowclient, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowclient, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowclient, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowclient, KKscrolledwindow, "KKscrolledwindow");
  GLADE_HOOKUP_OBJECT (windowclient, KKtreeview, "KKtreeview");
  GLADE_HOOKUP_OBJECT (windowclient, label38, "label38");
  GLADE_HOOKUP_OBJECT (windowclient, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowclient, label_nompren, "label_nompren");
  GLADE_HOOKUP_OBJECT (windowclient, label_max_paiments, "label_max_paiments");
  GLADE_HOOKUP_OBJECT (windowclient, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowclient, topclientref, "topclientref");
  GLADE_HOOKUP_OBJECT (windowclient, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowclient, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowclient, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowclient, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelpageprincipale, "KKlabelpageprincipale");
  GLADE_HOOKUP_OBJECT (windowclient, KKfixed2, "KKfixed2");
  GLADE_HOOKUP_OBJECT (windowclient, KKentryajoutid, "KKentryajoutid");
  GLADE_HOOKUP_OBJECT (windowclient, KKentryajoutnp, "KKentryajoutnp");
  GLADE_HOOKUP_OBJECT (windowclient, KKentryajoutvaleur, "KKentryajoutvaleur");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonajoutjour, "KKspinbuttonajoutjour");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonajoutmois, "KKspinbuttonajoutmois");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonajoutannee, "KKspinbuttonajoutannee");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmsgsucc, "KKlabelmsgsucc");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonajouter, "KKbuttonajouter");
  GLADE_HOOKUP_OBJECT (windowclient, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowclient, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowclient, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowclient, label22, "label22");
  GLADE_HOOKUP_OBJECT (windowclient, KKcomboboxajoutsexe, "KKcomboboxajoutsexe");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajoutvaleur, "KKlabelajoutvaleur");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajoutdate, "KKlabelajoutdate");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajoutnp, "KKlabelajoutnp");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajoutid, "KKlabelajoutid");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajoutsexe, "KKlabelajoutsexe");
  GLADE_HOOKUP_OBJECT (windowclient, label32, "label32");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelajouter, "KKlabelajouter");
  GLADE_HOOKUP_OBJECT (windowclient, KKfixed3, "KKfixed3");
  GLADE_HOOKUP_OBJECT (windowclient, KKentrymodifnp, "KKentrymodifnp");
  GLADE_HOOKUP_OBJECT (windowclient, KKentrymodifvaleur, "KKentrymodifvaleur");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonmodifjour, "KKspinbuttonmodifjour");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonmodifmois, "KKspinbuttonmodifmois");
  GLADE_HOOKUP_OBJECT (windowclient, KKspinbuttonmodifannee, "KKspinbuttonmodifannee");
  GLADE_HOOKUP_OBJECT (windowclient, KKbuttonconfirmermodif, "KKbuttonconfirmermodif");
  GLADE_HOOKUP_OBJECT (windowclient, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowclient, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowclient, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowclient, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowclient, KKcomboboxmodifsexe, "KKcomboboxmodifsexe");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifreus, "KKlabelmodifreus");
  GLADE_HOOKUP_OBJECT (windowclient, KKentrymodifid, "KKentrymodifid");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifsexe, "KKlabelmodifsexe");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifid, "KKlabelmodifid");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifnp, "KKlabelmodifnp");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifvaleur, "KKlabelmodifvaleur");
  GLADE_HOOKUP_OBJECT (windowclient, KKlabelmodifdate, "KKlabelmodifdate");
  GLADE_HOOKUP_OBJECT (windowclient, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowclient, label31, "label31");

  return windowclient;
}

